export const GET_RECIPE = 'GET_RECIPE';
export const GET_RECIPE_ERROR = 'GET_RECIPE_ERROR';
export const GET_RECIPE_PENDING = 'GET_RECIPE_PENDING';
export const ADD_RECIPE_PENDING = 'ADD_RECIPE_PENDING';
export const ADD_RECIPE = 'ADD_RECIPE';
export const ADD_RECIPE_ERROR = 'ADD_RECIPE_ERROR';
export const DELETE_RECIPE_ERROR = 'ADD_RECIPE_ERROR';
export const DELETE_RECIPE = 'DELETE_RECIPE';



